# action.yml
name: "ll-builder-build"
description: "linyaps builder action"
author: myml
inputs:
  files:
    description: "linglong.yaml file path"
    default: "linglong.yaml"
    required: true

branding:
  icon: align-center
  color: "white"

runs:
  using: "composite"
  steps:
    - name: Install
      shell: bash
      run: |
        echo "deb [trusted=yes] https://ppa.linyaps.org.cn/latest/xUbuntu_24.04/ ./" | sudo tee /etc/apt/sources.list.d/linglong.list
        sudo apt update
        sudo apt-get install -y --no-install-recommends linglong-builder linglong-box

    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/linglong-builder
        key: ${{ runner.os }}-linglong-builder-repo-objects

    - name: Build
      shell: bash
      run: |
        # export QT_LOGGING_RULES='*.debug=true'
        ll-builder --version
        ll-builder repo disable-mirror stable
        cat ~/.cache/linglong-builder/config.yaml
        curl https://repo-mirror.cicd.getdeepin.org/api/v2/mirrors/stable
        export LINYAPS_BACKTRACE=true
        export LINYAPS_LOG_LEVEL=debug
        echo contenturl=https://fi-1.edge.linyaps.org.cn/repos/stable/ >> 
        ll-builder build --skip-output-check
        ll-builder export --layer
